### ISSUE TITLE
Proper documentation and enable customization

### ISSUE THREAD

**Issue by chinnichaitanya** [HourlyNerd/angular-squire#2]
It would be great if the documentation is much detailed for noobs like me. 
Also making it customizable would be great.

**Comment by mkoryak** [comment]
what exactly about the docs would you like to see improved? 

and what kind of customizations are you looking for?

**Comment by chinnichaitanya** [comment]
There is no documentation for 
```<squire-cover>...</squire-cover>``` and also for ```<squire-controls>...</squire-controls>``` 
which are used here : http://hourlynerd.github.io/angular-squire/dist/ 
Regarding customization, it would be great if there is provision for adding different font-sizes, colors etc., and also removing some features according to the developer.

**Comment by mkoryak** [comment]
well the docs are a bit better now, customization next :)

**Comment by chinnichaitanya** [comment]
:+1: Waiting for it :)

**Comment by mkoryak** [comment]
here you go
https://github.com/HourlyNerd/angular-squire#changing-which-buttons-show-on-editor

**Comment by mkoryak** [comment]
im going to close this. you can change the buttons programmatically or override the template. you also can use the sass in the dist folder  to override variables etc and compile your own css
