### ISSUE TITLE
Installation failed with JSPM

### ISSUE THREAD

**Issue by monsendag** [HourlyNerd/angular-squire#3]
Hey mate!

The installation of angular-squire fails using JSPM:bower.

```
$ jspm install --save bower:angular-squire
    looking up bower:angular-squire
    updating registry cache...

err Registry squire-rte@git not found.
```

I realise that this is a very specific use case, but is it necessary to maintain your own fork of Squire?
Could it perhaps be possible to publish an NPM module as an alternative solution?

Thanks,
Dag

**Comment by mkoryak** [comment]
I would rather not have to maintain my own fork, but unfortunately our fork contains a fix that is required by hourlynerd. The lastest master of squire also has this fix, but as far as I know it hasnt been released yet.  
I dont use jspm, but you are saying that if this project was on npm, it would help solve that lookup issue?

**Comment by monsendag** [comment]
I understand, thanks for the quick reply :)

From what I could understand by browsing the fork, it adds the `isDefaultPrevented()` method to the event in the onPaste callback.
In the most recent release of Squire (1.3.0), it seems that they include this method: https://github.com/neilj/Squire/blob/v1.3.0/source/Editor.js#L1724

What do you think? Might be possible to retire the fork.

On another note, it would probably solve my issue if this was on npm, and my impression is that a lot of frontend code (including Squire) is now cross published. It is worth a consideration :)

**Comment by mkoryak** [comment]
I am talking about this code:
https://github.com/neilj/Squire/pull/105

which he hasnt released yet

**Comment by monsendag** [comment]
Ah, my bad.

This was quite recent. I'll just wait then and see what happens!

Thanks

**Comment by mkoryak** [comment]
another thing you can do is use angular-squire 0.6.2 which doesnt use that fork, since you probably dont need this iframe fix

**Comment by monsendag** [comment]
Good idea! I happen to use Karma as well, but can live without this for the time being.
