### ISSUE TITLE
SQ is not a function

### ISSUE THREAD

**Issue by tomismore** [HourlyNerd/angular-squire#8]
Can't seem to get past this error:

Uncaught TypeError: SQ is not a function

My best guess is that I'm using squire 1.4 when I need to be using squire 1.3 ... can you confirm that? 

Thanks! Love this module

**Comment by mkoryak** [comment]
are you including squire-rte ? I was including as part of dist for this for a bit, but have since removed it. you need to add it to your code yourself

**Comment by tomismore** [comment]
My mistake actually turned out to be running the angular-squire code BEFORE the squire code. Sorry--code blindness gets you when you least expect it.

Thanks again--it's a really nice directive.

**Comment by mkoryak** [comment]
Thanks, ill put in a todo to have a better error message if this happens.
